### ISSUE TITLE
Page titles

### ISSUE THREAD

**Issue by mgursch** [mhashim6/ViewPagerDSL#1]
Hey

thanks for this nice library :)

How can I setup page titles?

**Comment by mhashim6** [comment]
Hey, do you mean like a tag for fragments? if so, then It won't be necessary, as viewpager handles recycling fragments for you. 

Sorry, I've never used titles in viewpager, so, I don't understand. feel free to elaborate though!

Thanks!

**Comment by mhashim6** [comment]
Hey, I forgot about that, thanks for the suggestion!

**Comment by mhashim6** [comment]
done, see 1715a7ba0ba9f9306ecc4e0a52915a764e18db56
