### ISSUE TITLE
RuntimeException: pages() is not called

### ISSUE THREAD

**Issue by tekinalper** [mhashim6/ViewPagerDSL#3]
I get "Caused by: java.lang.RuntimeException: pages() is not called" error although there is a fragment in pages. Do you have an idea what might cause this?

**Comment by mhashim6** [comment]
this exception is thrown when the function pages() is never called.
are you sure you've called it and passed your fragments to it?

**Comment by tekinalper** [comment]
Yes, I am pretty sure as I click pages() function in fragment, it goes to the implementation in FragmentPagerAdapterDSL. There might be a resolution problem but I don't know why.

**Comment by mhashim6** [comment]
Is it possible to show your code?

**Comment by tekinalper** [comment]
Already changed to usual implementation. Will give a try with your code and mine again whenever I have time then will let you know.

**Comment by mhashim6** [comment]
Alright, I'll close the issue for now, feel free to reopen it with any updates.
